### ISSUE TITLE
Installation in QGIS 2.18 fails

### ISSUE THREAD

**Issue by patricknoack** [sommergis/agknow_qgis3#2]
Unzip files into .qgis/Python/plugins -> Metadatendatei fehlt
![image](https://user-images.githubusercontent.com/37699897/49872120-68757b00-fe18-11e8-9844-31a9b5e37d4d.png)

**Comment by sommergis** [comment]
Please make sure that the zipfile is unzipped to .qgis2\python\plugins\agknow_qgis
All files of the zipfile should be in this folder.

**Comment by patricknoack** [comment]
OK - Unzipped original file instead of folder in ZIP file.
Extension now available.
